# Generated by Django 2.0.3 on 2018-03-09 12:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DEM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rast', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
            ],
            options={
                'db_table': 'dem',
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='código')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326, verbose_name='geom')),
            ],
            options={
                'db_table': 'roads',
            },
        ),
    ]
